sudo: required
services:
  - docker

before_install:
  - docker build -t tero23/docker-react -f Dockerfile.dev .

script:
  - docker run tero23/docker-react npm run test -- --coverage
# deploy:
#   provider: elasticbeanstalk
#   region: "us-east-1"
#   app: "docker-react"
#   env: "Docker-env"
#   bucket_name: "nameOfTheS3BucketThatWasCreatedAutomatically"
#   bucket_path: "docker-react"
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key:
#     secure: "$AWS_SECRET_KEY"
